version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clean-node-api
    volumes:
      - .:/home/node/app
    environment:
      - NODE_ENV=production
      - NODE_PORT=3000
      - NODE_HOST=localhost
    ports:
      - "3000:3000"
